import { Router, Request, Response } from 'express';
import transporter from '../config/email';

const router = Router();

router.post('/', async (req: Request, res: Response) => {
  const { name, phone, message } = req.body;

  console.log(`\n📬 [Contact API] Received inquiry request:`);
  console.log(`   - Name : ${name}`);
  console.log(`   - Phone: ${phone}`);

  if (!name || !phone || !message) {
    console.log(`❌ [Contact API] Rejected: Missing required fields.`);
    return res.status(400).json({
      success: false,
      message: 'All fields (Name, Phone, Message) are required.',
    });
  }

  try {
    const adminEmail = process.env.EMAIL_USER || 'haider.sqa98@gmail.com';
    const recipientEmail = 'haider.sqa98@gmail.com';

    console.log(`📧 [Contact API] Verifying connection and sending email to: ${recipientEmail}...`);

    const mailOptions = {
      from: `"DivineCraft Contact Form" <${adminEmail}>`,
      to: recipientEmail,
      subject: `New Customer Inquiry from ${name}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e0e0e0; border-radius: 8px; background-color: #ffffff;">
          <h2 style="color: #3D1F0D; border-bottom: 2px solid #B8860B; padding-bottom: 10px; font-weight: normal; margin-top: 0;">New Customer Inquiry</h2>
          <p style="font-size: 14px; color: #1C1C1C; margin-top: 20px;">You have received a new message from the DivineCraft contact form:</p>
          <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
            <tr>
              <td style="padding: 10px 0; font-weight: bold; color: #7A6A5A; border-bottom: 1px solid #f0f0f0; width: 120px;">Name:</td>
              <td style="padding: 10px 0; color: #1C1C1C; border-bottom: 1px solid #f0f0f0;">${name}</td>
            </tr>
            <tr>
              <td style="padding: 10px 0; font-weight: bold; color: #7A6A5A; border-bottom: 1px solid #f0f0f0;">Phone:</td>
              <td style="padding: 10px 0; color: #1C1C1C; border-bottom: 1px solid #f0f0f0;">${phone}</td>
            </tr>
            <tr>
              <td style="padding: 10px 0; font-weight: bold; color: #7A6A5A; vertical-align: top; padding-top: 10px;">Message:</td>
              <td style="padding: 10px 0; color: #1C1C1C; padding-top: 10px; line-height: 1.6;">${message}</td>
            </tr>
          </table>
          <div style="margin-top: 30px; font-size: 11px; color: #7A6A5A; border-top: 1px solid #f0f0f0; padding-top: 15px; text-align: center;">
            This email was automatically generated by the DivineCraft website contact form.
          </div>
        </div>
      `,
    };

    const info = await transporter.sendMail(mailOptions);
    
    console.log(`✅ [Contact API] Connection: Transporter verification succeeded!`);
    console.log(`✅ [Contact API] Result: Email sent successfully!`);
    console.log(`   - Message ID: ${info.messageId}`);

    return res.status(200).json({
      success: true,
      message: 'Your inquiry has been sent successfully.',
    });
  } catch (error: any) {
    console.error(`❌ [Contact API] Failed to send email:`, error.message || error);
    return res.status(500).json({
      success: false,
      message: 'Failed to send inquiry. Please try again later.',
    });
  }
});

export default router;
